### ISSUE TITLE
v5: GLFW-Related Issue: GCS will not start

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs#510]
Booted up today, and GCS seems to no longer be opening. I don't think I made any system changes between when it last worked and when it stopped working.

Stack Trace:
```
panic: NotInitialized: The GLFW library is not initialized

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError({0x0, 0x0, 0x0?})
        /home/nick/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20220806181222-55e207c401ad/error.go:174 +0x1d9
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
        /home/nick/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20220806181222-55e207c401ad/error.go:185
github.com/go-gl/glfw/v3.3/glfw.PostEmptyEvent()
        /home/nick/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20220806181222-55e207c401ad/window.go:1022 +0x33
github.com/richardwilkes/unison.InvokeTask(0x180b8c8)
        /home/nick/go/pkg/mod/github.com/richardwilkes/unison@v0.28.1-0.20220815034014-8b6e7a9a53d4/task.go:32 +0x105
github.com/richardwilkes/unison.SetColorMode(...)
        /home/nick/go/pkg/mod/github.com/richardwilkes/unison@v0.28.1-0.20220815034014-8b6e7a9a53d4/app.go:280
github.com/richardwilkes/gcs/v5/model/settings.Global()
        /home/nick/git/gcs/model/settings/settings.go:86 +0x2e5
main.main()
        /home/nick/git/gcs/main.go:51 +0x450
```

**Comment by richardwilkes** [comment]
Odd. It’s running fine for me. Could you use git bisect to determine at what point things went bad for you? Also, which platform? It’s possible I forgot to do something on one of the non-Mac platforms, since I only fire those up when I know I definitely need to look at them.

- Rich

**Comment by rinickolous** [comment]
I don't think it's an issue introduced with a recent commit, because there haven't been any in a few days, and this only started today.

**Comment by rinickolous** [comment]
I think I know what does this. Where does GCS v5 store its global settings?

**Comment by rinickolous** [comment]
Quick update:
I commented out the contents of `SetColorMode` in `unison/app.go`, and the program now launches.

**Comment by richardwilkes** [comment]
OK, I’ll take a look at what is going on there. Probably just a sequencing issue, since you can’t use anything in glfw until you init it.

**Comment by lucasrpatten** [comment]
I am having a similar problem - 
`OS: Kali GNU/Linux Rolling on Gnome`
`amd64`
`Go version 1.19`
```
Error Message:
FTL | 2022-08-22 | 22:35:57.929 | VersionUnavailable: GLX: Failed to create context: GLXBadFBConfig
                                      [github.com/richardwilkes/unison.NewWindow] github.com/richardwilkes/unison@v0.28.1-0.20220815034014-8b6e7a9a53d4/window.go:200
                                      [github.com/richardwilkes/gcs/v5/ui.Start.func1] startup.go:31
                                      [github.com/richardwilkes/toolbox.CallWithHandler] github.com/richardwilkes/toolbox@v1.72.1/call.go:25
                                      [github.com/richardwilkes/toolbox.Call] github.com/richardwilkes/toolbox@v1.72.1/call.go:19
                                      [github.com/richardwilkes/unison.finishStartup] github.com/richardwilkes/unison@v0.28.1-0.20220815034014-8b6e7a9a53d4/app.go:189
                                      [github.com/richardwilkes/toolbox.CallWithHandler] github.com/richardwilkes/toolbox@v1.72.1/call.go:25
                                      [github.com/richardwilkes/unison.processNextTask] github.com/richardwilkes/unison@v0.28.1-0.20220815034014-8b6e7a9a53d4/task.go:52
                                      [github.com/richardwilkes/unison.processEvents] github.com/richardwilkes/unison@v0.28.1-0.20220815034014-8b6e7a9a53d4/app.go:170
                                      [github.com/richardwilkes/unison.Start] github.com/richardwilkes/unison@v0.28.1-0.20220815034014-8b6e7a9a53d4/app.go:164
                                      [github.com/richardwilkes/gcs/v5/ui.Start] startup.go:28
                                      [main.main] main.go:65
```

**Comment by lucasrpatten** [comment]
build command:
```
sudo ./build.sh -a
Building...
Testing with -race enabled...
?       github.com/richardwilkes/gcs/v5 [no test files]
?       github.com/richardwilkes/gcs/v5/constants       [no test files]
?       github.com/richardwilkes/gcs/v5/dbg     [no test files]
?       github.com/richardwilkes/gcs/v5/gen     [no test files]
?       github.com/richardwilkes/gcs/v5/model/crc       [no test files]
?       github.com/richardwilkes/gcs/v5/model/criteria  [no test files]
?       github.com/richardwilkes/gcs/v5/model/export    [no test files]
?       github.com/richardwilkes/gcs/v5/model/fxp       [no test files]
?       github.com/richardwilkes/gcs/v5/model/gurps     [no test files]
?       github.com/richardwilkes/gcs/v5/model/gurps/ancestry    [no test files]
?       github.com/richardwilkes/gcs/v5/model/gurps/attribute   [no test files]
?       github.com/richardwilkes/gcs/v5/model/gurps/datafile    [no test files]
?       github.com/richardwilkes/gcs/v5/model/gurps/equipment   [no test files]
?       github.com/richardwilkes/gcs/v5/model/gurps/export      [no test files]
?       github.com/richardwilkes/gcs/v5/model/gurps/feature     [no test files]
?       github.com/richardwilkes/gcs/v5/model/gurps/gid [no test files]
ok      github.com/richardwilkes/gcs/v5/model/gurps/measure     (cached)
?       github.com/richardwilkes/gcs/v5/model/gurps/nameables   [no test files]
?       github.com/richardwilkes/gcs/v5/model/gurps/prereq      [no test files]
?       github.com/richardwilkes/gcs/v5/model/gurps/settings    [no test files]
?       github.com/richardwilkes/gcs/v5/model/gurps/skill       [no test files]
?       github.com/richardwilkes/gcs/v5/model/gurps/spell       [no test files]
?       github.com/richardwilkes/gcs/v5/model/gurps/trait       [no test files]
?       github.com/richardwilkes/gcs/v5/model/gurps/weapon      [no test files]
?       github.com/richardwilkes/gcs/v5/model/id        [no test files]
?       github.com/richardwilkes/gcs/v5/model/jio       [no test files]
?       github.com/richardwilkes/gcs/v5/model/library   [no test files]
ok      github.com/richardwilkes/gcs/v5/model/paper     (cached)
?       github.com/richardwilkes/gcs/v5/model/settings  [no test files]
?       github.com/richardwilkes/gcs/v5/model/settings/display  [no test files]
?       github.com/richardwilkes/gcs/v5/model/theme     [no test files]
?       github.com/richardwilkes/gcs/v5/pdf     [no test files]
?       github.com/richardwilkes/gcs/v5/res     [no test files]
?       github.com/richardwilkes/gcs/v5/setup   [no test files]
?       github.com/richardwilkes/gcs/v5/setup/trampolines       [no test files]
?       github.com/richardwilkes/gcs/v5/setup/trampolines2      [no test files]
?       github.com/richardwilkes/gcs/v5/ui      [no test files]
?       github.com/richardwilkes/gcs/v5/ui/about        [no test files]
?       github.com/richardwilkes/gcs/v5/ui/menus        [no test files]
?       github.com/richardwilkes/gcs/v5/ui/updates      [no test files]
?       github.com/richardwilkes/gcs/v5/ui/widget       [no test files]
?       github.com/richardwilkes/gcs/v5/ui/widget/ntable        [no test files]
?       github.com/richardwilkes/gcs/v5/ui/workspace    [no test files]
?       github.com/richardwilkes/gcs/v5/ui/workspace/editors    [no test files]
?       github.com/richardwilkes/gcs/v5/ui/workspace/external   [no test files]
?       github.com/richardwilkes/gcs/v5/ui/workspace/lists      [no test files]
?       github.com/richardwilkes/gcs/v5/ui/workspace/settings   [no test files]
?       github.com/richardwilkes/gcs/v5/ui/workspace/settings/attrdef   [no test files]
?       github.com/richardwilkes/gcs/v5/ui/workspace/settings/body      [no test files]
?       github.com/richardwilkes/gcs/v5/ui/workspace/sheet      [no test files]
Linting...
```

**Comment by lucasrpatten** [comment]
It looks like I may need opengl 3.3, rather then 3.0... which is rather unfortunate, as my device is relatively new and is a mid-tier laptop

**Comment by richardwilkes** [comment]
@lucasrpatten your issue is not related to the original issue, which is merely an initialization order issue triggered by setting the theme to something besides “automatic”.

As you’ve discovered, OpenGL 3.3 (or maybe 3.2 — I’d have to check) is indeed required. OpenGL 3.3 was released 12 years ago, so I have no intention of backing down the requirements for that.

**Comment by richardwilkes** [comment]
The problem you hit with OpenGL may just be some specific option I’ve chosen, however — if we can narrow down the problem setting, I can then determine if it is really necessary or not, and if not, remove or reduce the option to a lesser one that is more widely compatible.

**Comment by lucasrpatten** [comment]
I've found the problem out - its a driver issue. My graphics drivers (AMD Radeon) aren't supported on kali. I can develop on windows (but... windows...). I will look and see if there is a setting that can be backtracked. Otherwise, don't worry about it.

**Comment by richardwilkes** [comment]
This was actually a problem in unison. Updated to unison v0.29.1, which contains the fix.
